---
- 
  get_url: "url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz validate_certs=no"
  name: "Download WordPress"
- 
  become: true
  name: "Extract WordPress"
  unarchive: "src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no"
- 
  become: true
  lineinfile: "dest=/etc/apache2/sites-enabled/000-default.conf regexp=\"(.)+DocumentRoot /var/www/html\" line=\"DocumentRoot /var/www/wordpress\""
  name: "Update default Apache site"
  notify: "restart apache"
- 
  become: true
  command: "mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php"
  name: "Copy sample config file"
- 
  become: true
  lineinfile: dest=/var/www/wordpress/wp-config.php regexp=\"{{ item.regexp }}\" line=\"{{ item.line }}\"
  name: "Update WordPress config file"
  with_items: 
    - 
      line: define( 'DB_NAME', '{{wp_mysql_db}}' );
      regexp: define\\( 'DB_NAME', '(.)+'\\ );
    - 
      line: define( 'DB_USER', '{{wp_mysql_user}}' );
      regexp: define\\( 'DB_USER', '(.)+'\\ );
    - 
      line: define( 'DB_PASSWORD', '{{wp_mysql_password}}' );
      regexp: define\\( 'DB_PASSWORD', '(.)+'\\ );
